(function(){
'use strict';
const C=DashboardCore,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={executive:'Executive overview',sales:'Sales performance',marketing:'Marketing performance',finance:'Financial overview',operations:'Operations & supply chain'};
const subtitles={executive:'A connected view of business performance and strategic targets.',sales:'Understand revenue, products, regions and opportunity conversion.',marketing:'Measure channel efficiency, campaign returns and acquisition.',finance:'Track revenue, expenses, cash movement and planning variance.',operations:'Monitor fulfillment, suppliers, stock levels and delivery delays.'};
let data=C.demo(),sample=true,view='executive',page=0,displayRows=[],searchRows=[];
const num=v=>v===null?'—':new Intl.NumberFormat('en-IN',{maximumFractionDigits:1}).format(v),money=v=>v===null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:Math.abs(v)>=100000?1:2,notation:Math.abs(v)>=100000?'compact':'standard'}).format(v),pct=v=>v===null?'—':`${num(v*100)}%`;
const key=()=>view==='executive'?'finance':view,filters=()=>({from:$('from').value,to:$('to').value,region:$('region').value,team:$('team').value}),rows=k=>C.filter(data[k],filters()),total=(r,k)=>C.sum(r,k);
function card(label,value,note){return `<article class="kpi"><span class="label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;}
function panel(title,content,note=''){return `<section class="panel"><h2>${esc(title)}</h2>${note?`<p class="note">${esc(note)}</p>`:''}${content}</section>`;}
const empty=()=>'<p class="empty">No matching records. Adjust filters or import data.</p>';
function table(headers,values){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${values.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function bars(items,format=num){if(!items.length)return empty();const max=Math.max(...items.map(x=>x.value),1);return items.map(x=>`<div class="bar-row"><span>${esc(x.label)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,x.value/max*100)}%"></div></div><strong>${esc(format(x.value))}</strong></div>`).join('');}
function chart(r,keys,labels){const values=C.series(r,keys,$('group').value,filters().from,filters().to);if(!values.length)return empty();const colors=['#386bda','#24a091','#df9531'];const max=Math.max(...values.flatMap(x=>keys.map(k=>x[k])),1),x=i=>45+i*480/Math.max(values.length-1,1),y=v=>190-v/max*165;
 return `<div class="legend">${labels.map((l,i)=>`<span style="--series:${colors[i]}">${esc(l)}</span>`).join('')}</div><svg class="chart" viewBox="0 0 555 225" role="img" aria-label="${esc(labels.join(' and '))} by period"><title>${esc(labels.join(' and '))} by period; values in INR. Exact values below.</title>${[0,.5,1].map(t=>`<line x1="45" x2="530" y1="${y(max*t)}" y2="${y(max*t)}"/><text x="0" y="${y(max*t)+4}">${esc(money(max*t))}</text>`).join('')}${keys.map((k,j)=>`<polyline fill="none" stroke="${colors[j]}" stroke-width="2.5" points="${values.map((v,i)=>`${x(i)},${y(v[k])}`).join(' ')}"/>${values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v[k])}" r="3" fill="${colors[j]}"><title>${esc(v.label+': '+labels[j]+' '+money(v[k]))}</title></circle>`).join('')}`).join('')}${values.filter((v,i)=>i===0||i===values.length-1||i%Math.ceil(values.length/5)===0).map(v=>`<text text-anchor="middle" x="${x(values.indexOf(v))}" y="215">${esc(v.label)}</text>`).join('')}</svg><details><summary>View exact trend values</summary>${table(['Period',...labels],values.map(v=>[v.label,...keys.map(k=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v[k]))]))}</details>`;
}
function groupedRates(r,dimension,measure,denominator){return [...new Set(r.map(x=>x[dimension]))].map(label=>{const subset=r.filter(x=>x[dimension]===label);return [label,num(total(subset,measure)),num(total(subset,denominator)),pct(C.ratio(total(subset,measure),total(subset,denominator)))];});}
function render(){
 if($('from').value&&$('to').value&&$('from').value>$('to').value){$('status').textContent='Start date must be on or before end date.';$('kpis').innerHTML='';$('panels').innerHTML='';displayRows=[];renderRecords();return;}
 $('status').textContent='';$('title').textContent=names[view];$('subtitle').textContent=subtitles[view];document.title=`${names[view]} | Dimple Enterprises`;document.querySelectorAll('#views a').forEach(a=>a.setAttribute('aria-current',a.dataset.view===view?'page':'false'));
 const f=rows('finance'),s=rows('sales'),m=rows('marketing'),o=rows('operations'),t=rows('targets'),won=s.filter(r=>r.stage==='Won'),delivered=o.filter(r=>r.status==='Delivered'),revenue=total(f,'revenue'),cost=total(f,'cost'),customers=total(won,'customers');
 $('source-label').textContent=sample?'SAMPLE DATA · Illustrative business, not live results':'IMPORTED WORKSPACE · Local to this tab';
 const dates=data[key()].map(r=>r.date).sort();$('coverage').textContent=dates.length?`Source coverage: ${dates[0]} – ${dates.at(-1)}`:'No source records';let k=[],p=[];
 if(view==='executive'){
 const current=filters(),span=current.from&&current.to?Math.round((Date.parse(current.to)-Date.parse(current.from))/86400000)+1:0;let growth=null;
 if(span){const end=new Date(Date.parse(current.from)-86400000).toISOString().slice(0,10),start=new Date(Date.parse(end)-(span-1)*86400000).toISOString().slice(0,10),prior=C.filter(data.finance,{...current,from:start,to:end});if(prior.length)growth=C.ratio(revenue-total(prior,'revenue'),total(prior,'revenue'));}
 k=[card('Revenue',f.length?money(revenue):'—','Finance ledger · INR'),card('Operating profit',f.length?money(revenue-cost):'—','Revenue less recorded costs'),card('Revenue growth',pct(growth),'Previous equal-length date window; — if unavailable'),card('New customers',s.length?num(customers):'—','Sum of new customers on won opportunities')];
 p=[panel('Revenue & costs',chart(f,['revenue','cost'],['Revenue','Costs'])),panel('Revenue by region',bars(C.aggregate(f,'region','revenue'),money),'Regional revenue indicates market mix; expansion requires historical context.'),panel('Team performance',table(['Team','Revenue','Profit','New customers'],[...new Set([...f,...s].map(r=>r.team))].map(team=>{const a=f.filter(r=>r.team===team),b=won.filter(r=>r.team===team);return[team,money(total(a,'revenue')),money(total(a,'revenue')-total(a,'cost')),num(total(b,'customers'))];}))),panel('Strategic targets',t.length?table(['Metric','Actual','Target','Attainment'],['revenue','customers','fulfilledOrders'].map(metric=>{const targetRows=t.filter(r=>r.metric===metric),target=total(targetRows,'target'),actual={revenue,customers,fulfilledOrders:delivered.length}[metric];return[metric,metric==='revenue'?money(actual):num(actual),targetRows.length?(metric==='revenue'?money(target):num(target)):'—',pct(C.ratio(actual,target))];})):empty(),'Targets sum across the selected dates, regions and teams. Align imported target periods with actuals.')];
 }else if(view==='sales'){
 k=[card('Won revenue',s.length?money(total(won,'revenue')):'—','Realized revenue from Won opportunities'),card('Won opportunities',s.length?num(won.length):'—',`${s.length} opportunities in selection`),card('Lead-to-win conversion',pct(C.ratio(won.length,s.length)),'Won opportunities / all opportunities'),card('Average won value',money(C.ratio(total(won,'revenue'),won.length)),'Won revenue / won opportunities')];
 p=[panel('Sales trend',chart(won,['revenue','cost'],['Won revenue','Direct costs'])),panel('Top products',bars(C.aggregate(won,'product','revenue'),money)),panel('Revenue by region',bars(C.aggregate(won,'region','revenue'),money)),panel('Opportunity pipeline',bars(['Lead','Qualified','Proposal','Won','Lost'].map(label=>({label,value:s.filter(r=>r.stage===label).length}))),'Current-stage counts, not historical stage-to-stage conversion.')];
 }else if(view==='marketing'){
 const spend=total(m,'spend'),aRevenue=total(m,'attributedRevenue');k=[card('Campaign ROI',pct(C.ratio(aRevenue-spend,spend)),'(Attributed revenue − spend) / spend; excludes delivery costs'),card('Acquisition cost',money(C.ratio(spend,total(m,'customers'))),'Spend / attributed new customers'),card('Click-through rate',pct(C.ratio(total(m,'clicks'),total(m,'impressions'))),'Clicks / impressions'),card('Cost per 1,000 impressions',money(C.ratio(spend*1000,total(m,'impressions'))),'Spend / impressions × 1,000')];
 p=[panel('Campaign spend & return',chart(m,['spend','attributedRevenue'],['Spend','Attributed revenue'])),panel('Website traffic & conversions',table(['Channel','Leads','Visits','Visit-to-lead rate'],groupedRates(m,'channel','leads','visits'))),panel('Channel engagement',bars(C.aggregate(m,'channel','engagements')),'Interactions counted by your source; not unique people.'),panel('Channel efficiency',table(['Channel','Spend','Customers','CAC','ROI'],[...new Set(m.map(r=>r.channel))].map(channel=>{const r=m.filter(x=>x.channel===channel),spend=total(r,'spend');return[channel,money(spend),num(total(r,'customers')),money(C.ratio(spend,total(r,'customers'))),pct(C.ratio(total(r,'attributedRevenue')-spend,spend))];})))];
 }else if(view==='finance'){
 const budget=total(f,'budget');k=[card('Revenue',f.length?money(revenue):'—','Finance ledger · INR'),card('Profit margin',pct(C.ratio(revenue-cost,revenue)),'(Revenue − costs) / revenue'),card('Net cash flow',f.length?money(total(f,'cashIn')-total(f,'cashOut')):'—','Cash received less cash paid'),card('Budget utilization',pct(C.ratio(cost,budget)),'Actual costs / expense budget')];
 p=[panel('Revenue vs costs',chart(f,['revenue','cost'],['Revenue','Costs'])),panel('Cash movement',chart(f,['cashIn','cashOut'],['Cash in','Cash out'])),panel('Forecast & actual revenue',chart(f,['revenue','forecast'],['Actual revenue','Revenue forecast'])),panel('Budget & forecast variance',table(['Measure','Planned','Actual','Actual − planned'],[['Expense budget',money(budget),money(cost),money(cost-budget)],['Revenue forecast',money(total(f,'forecast')),money(revenue),money(revenue-total(f,'forecast'))]]),'Positive expense variance means overspend. Positive revenue variance means above forecast.')];
 }else{
 const stock=C.inventory(o),onTime=delivered.filter(r=>r.deliveredDate<=r.dueDate),asOf=filters().to||new Date().toISOString().slice(0,10),delays=o.filter(r=>r.status==='Delayed'||r.status!=='Delivered'&&r.dueDate<asOf||r.status==='Delivered'&&r.deliveredDate>r.dueDate);
 k=[card('Order fulfillment',pct(C.ratio(delivered.length,o.length)),'Delivered orders / all orders'),card('On-time delivery',pct(C.ratio(onTime.length,delivered.length)),'On-time delivered / delivered orders'),card('Inventory units',stock.length?num(total(stock,'inventory')):'—','Latest row per region + supplier + product in selection'),card('Average lead time',o.length?`${num(total(o,'leadDays')/o.length)} days`:'—','Mean supplied leadDays per order')];
 p=[panel('Order status',bars(['Pending','Processing','Delivered','Delayed'].map(label=>({label,value:o.filter(r=>r.status===label).length})))),panel('Inventory watch',stock.length?table(['Region / supplier / product','Stock','Reorder at','State'],stock.map(r=>[`${r.region} / ${r.supplier} / ${r.product}`,num(r.inventory),num(r.reorderPoint),r.inventory<=r.reorderPoint?'Reorder':'Available'])):empty()),panel('Supplier performance',table(['Supplier','Orders','Delivered','On-time rate','Lead days'],[...new Set(o.map(r=>r.supplier))].map(supplier=>{const all=o.filter(r=>r.supplier===supplier),done=all.filter(r=>r.status==='Delivered');return[supplier,num(all.length),num(done.length),pct(C.ratio(done.filter(r=>r.deliveredDate<=r.dueDate).length,done.length)),num(total(all,'leadDays')/all.length)];}))),panel('Bottlenecks & delivery delays',delays.length?table(['Order','Supplier','Due','Delivered','Status'],delays.map(r=>[r.id,r.supplier,r.dueDate,r.deliveredDate||'—',r.status])):'<p class="empty">No delays in this selection.</p>',`Late delivered orders, explicit delays and open orders overdue as of ${asOf}.`)];
 }
 $('kpis').innerHTML=k.join('');$('panels').innerHTML=p.join('');displayRows=rows(key());page=0;renderRecords();
}
function renderRecords(){const query=$('search').value.trim().toLowerCase();searchRows=displayRows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(query)));const headers=C.fields(key());const count=Math.max(1,Math.ceil(searchRows.length/15));page=Math.min(page,count-1);$('records').innerHTML=searchRows.length?`<table><thead><tr><th>Details</th>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${searchRows.slice(page*15,page*15+15).map((r,i)=>`<tr><td><button data-record="${page*15+i}" aria-label="Inspect record ${esc(r.id)}">Inspect</button></td>${headers.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:empty();$('page').textContent=`Page ${page+1} of ${count} · ${searchRows.length} records`;$('previous').disabled=page===0;$('next').disabled=page===count-1;}
function options(){const all=Object.values(data).flat();for(const name of ['region','team']){const old=$(name).value;$(name).innerHTML='<option value="">All '+name+'s</option>'+[...new Set(all.map(r=>r[name]))].sort().map(v=>`<option>${esc(v)}</option>`).join('');if([...$(name).options].some(o=>o.value===old))$(name).value=old;}const dates=all.map(r=>r.date).sort();$('from').value=dates[0]||'';$('to').value=dates.at(-1)||'';}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('views').innerHTML=Object.entries(names).map(([k,label],i)=>`<a href="#${k}" data-view="${k}"><span>0${i+1}</span>${esc(label.replace(' overview','').replace(' performance',''))}</a>`).join('');
function navigate(){const selected=location.hash.slice(1);if(names[selected])view=selected;render();}window.addEventListener('hashchange',navigate);
for(const id of ['from','to','region','team','group'])$(id).addEventListener('change',render);
$('reset').onclick=()=>{$('region').value='';$('team').value='';$('search').value='';options();render();};$('search').oninput=()=>{page=0;renderRecords();};$('previous').onclick=()=>{page--;renderRecords();};$('next').onclick=()=>{page++;renderRecords();};
$('records').onclick=e=>{const button=e.target.closest('[data-record]');if(!button)return;const row=searchRows[Number(button.dataset.record)];$('detail-content').innerHTML='<dl>'+Object.entries(row).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')+'</dl>';$('detail').showModal();};$('close-detail').onclick=()=>$('detail').close();
$('export').onclick=()=>{download(`${view}-${sample?'sample':'imported'}-records.csv`,C.csv(searchRows,C.fields(key())),'text/csv;charset=utf-8');$('status').textContent=`Exported ${searchRows.length} filtered ${key()} records. Executive exports use the finance ledger. Record search also applies.`;};$('print').onclick=()=>window.print();
$('dataset').innerHTML=Object.keys(C.schemas).map(k=>`<option>${k}</option>`).join('');
$('template').onclick=()=>download(`${$('dataset').value}-template.csv`,C.csv([],C.fields($('dataset').value)),'text/csv;charset=utf-8');
$('backup').onclick=()=>download(`business-workspace-${sample?'sample':'imported'}.json`,JSON.stringify({version:1,sample,exportedAt:new Date().toISOString(),datasets:data},null,2),'application/json');
$('file').onchange=async e=>{const file=e.target.files[0],dataset=$('dataset').value;if(!file)return;try{if(file.size>10*1024*1024)throw Error('File limit is 10 MB.');const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const input=JSON.parse(text),next=C.workspace(input);data=next;sample=input.sample===true;}else if(file.name.toLowerCase().endsWith('.csv')){const next=C.validate(dataset,C.parseCSV(text,C.fields(dataset)));if(sample){data=Object.fromEntries(Object.keys(C.schemas).map(k=>[k,[]]));}data[dataset]=next;sample=false;}else throw Error('Choose a .csv or .json file.');$('search').value='';options();render();$('import-status').textContent=`Imported ${file.name}. ${Object.values(data).reduce((n,r)=>n+r.length,0)} total rows. Sample datasets are removed when importing your first CSV.`;}catch(err){$('import-status').textContent=`Import rejected: ${err.message} Existing data was preserved.`;}e.target.value='';};
$('clear').onclick=()=>{if(!confirm('Clear this tab’s workspace? Download a backup first if needed.'))return;data=Object.fromEntries(Object.keys(C.schemas).map(k=>[k,[]]));sample=false;options();render();$('import-status').textContent='Empty workspace ready for your data.';};
$('demo').onclick=()=>{if(!sample&&!confirm('Replace imported data with sample data? Download a backup first if needed.'))return;data=C.demo();sample=true;options();render();$('import-status').textContent='Sample workspace loaded.';};
$('definitions').innerHTML=`<p>All monetary values are INR. Each row must have a unique id within its dataset and an ISO date (YYYY-MM-DD). Numerical fields are required and non-negative. Blank is not treated as zero. Ratios with zero denominators display —. Missing trend periods are shown as zero recorded activity; imports must cover the full period for valid interpretation.</p><p>Sales: one current opportunity per row, dated by creation/cohort date; only Won rows carry realized revenue, cost and new customers. Marketing: non-overlapping period/channel aggregates with deduplicated attributed customers. Finance: non-overlapping ledger totals; do not repeat the same budget/forecast across multiple rows. Operations: one current order per row; inventory is a snapshot, not an additive order measure. The latest dated order row per region/supplier/product supplies its inventory (id breaks same-date ties). Targets: one non-overlapping allocation per date/region/team/metric.</p><p>Executive revenue comes from finance; acquisition comes from sales. Marketing attribution is separate and must not be added to sales revenue. All date filters use the row’s date. Partial target periods are not prorated. Growth compares the previous equally long calendar window. No live systems are connected.</p>${Object.entries(C.schemas).map(([k,s])=>`<h3>${esc(k)}</h3><p><code>${C.fields(k).join(', ')}</code></p>${s.enums?Object.entries(s.enums).map(([f,v])=>`<p>${f}: ${v.join(', ')}</p>`).join(''):''}`).join('')}`;
options();navigate();
})();
