const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../js/dashboard-core.js'),R=require('../js/dashboard-reporting.js');
test('add and edit records validate without changing the original workspace',()=>{const d=C.demo(),row={...d.sales[0],id:'NEW1',revenue:10000};const next=R.updateRecord(d,'sales',row);assert.equal(next.sales.length,d.sales.length+1);assert.equal(next.finance,d.finance);const edited=R.updateRecord(next,'sales',{...row,revenue:20000},row.id);assert.equal(edited.sales.at(-1).revenue,20000);assert.equal(next.sales.at(-1).revenue,10000);});
test('record edits reject duplicate IDs, renamed IDs, invalid business values and missing records',()=>{const d=C.demo(),r=d.sales[0];assert.throws(()=>R.updateRecord(d,'sales',r),/duplicate/);assert.throws(()=>R.updateRecord(d,'sales',{...r,id:'renamed'},r.id),/cannot be changed/);assert.throws(()=>R.updateRecord(d,'sales',{...r,revenue:-1},r.id),/non-negative/);assert.throws(()=>R.updateRecord(d,'sales',r,'MISSING'),/no longer exists/);});
test('deleting a record returns an immutable workspace and rejects missing IDs',()=>{const d=C.demo(),id=d.sales[0].id,next=R.deleteRecord(d,'sales',id);assert.equal(next.sales.length,d.sales.length-1);assert.equal(d.sales[0].id,id);assert.equal(next.finance,d.finance);assert.throws(()=>R.deleteRecord(next,'sales',id),/no longer exists/);});
test('financial alerts use filtered weighted totals and do not alert on missing data',()=>{const d=C.demo(),f={region:'South'};let rules={...R.defaultRules,margin:60};const a=R.alerts(d,'finance',f,rules);assert.ok(a.some(x=>x.label==='Profit margin below threshold'));assert.ok(!a.some(x=>x.dataset==='operations'));assert.equal(R.alerts(d,'finance',{region:'Absent'},rules).length,0);assert.ok(!R.alerts(d,'finance',f,{...rules,margin:0}).some(x=>x.label==='Profit margin below threshold'));});
test('operations alerts use latest inventory snapshots and exact overdue days',()=>{const d=C.demo();d.operations=[{...d.operations[0],id:'O1',date:'2026-01-01',dueDate:'2026-01-10',status:'Processing',inventory:1,reorderPoint:5},{...d.operations[0],id:'O2',date:'2026-01-02',dueDate:'2026-01-10',status:'Delivered',deliveredDate:'2026-01-12',inventory:10,reorderPoint:5}];const notices=R.alerts(d,'operations',{from:'2026-01-01',to:'2026-01-15'},{...R.defaultRules,lateDays:3});assert.equal(notices.length,1);assert.equal(notices[0].id,'O1');assert.match(notices[0].detail,/5 days/);});
test('alert threshold validation rejects blanks, nonfinite values and fractional overdue days',()=>{for(const v of ['',null,Infinity,-1,101])assert.throws(()=>R.validateRules({...R.defaultRules,margin:v}));assert.throws(()=>R.validateRules({...R.defaultRules,lateDays:1.5}));assert.deepEqual(R.validateRules({margin:'20',roi:'-10',conversion:'30',budget:'100',lateDays:'2'}),{margin:20,roi:-10,conversion:30,budget:100,lateDays:2});});
test('summary reports include active scope, comparisons and safe escaped imported text',()=>{const d=C.demo();d.operations=[{...d.operations[0],supplier:'<script>alert(1)</script>',inventory:0,reorderPoint:5}];const report=R.summaryReport(d,'operations',{from:'2026-01-01',to:'2026-01-31',region:'South'},true,R.defaultRules,'2026-09-18T10:00:00Z');assert.match(report,/SAMPLE DATA/);assert.match(report,/Region: South/);assert.match(report,/Previous period/);assert.match(report,/&lt;script&gt;/);assert.doesNotMatch(report,/<script>/);assert.match(report,/Content-Security-Policy/);assert.match(report,/Alert thresholds/);});
